apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          startingDeadlineSeconds: 60
          ttlSecondsAfterFinished: 600
          restartPolicy: OnFailure
          containers:
          - name: clearsessions
            image: django_app:latest
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            envFrom:
            - secretRef:
                name: secret
