apiVersion: v1
kind: Pod
metadata:
  name: django
  labels:
    app: django
spec:
  containers:
  - name: django
    image: django_app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
    envFrom:
            - secretRef:
                name: secret