apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: clearsessions
            image: django_app:latest
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            env:
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: secret
                    key: SECRET_KEY
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: secret
                    key: DATABASE_URL
              - name: DEBUG
                valueFrom:
                  secretKeyRef:
                    name: secret
                    key: DEBUG
              - name: ALLOWED_HOSTS
                valueFrom:
                  secretKeyRef:
                    name: secret
                    key: ALLOWED_HOSTS
