apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: django_app:latest
        imagePullPolicy: Never
        command: ["python", "manage.py", "migrate"]
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret
                key: SECRET_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: secret
                key: DATABASE_URL
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: secret
                key: DEBUG
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: secret
                key: ALLOWED_HOSTS

