apiVersion: v1
kind: Pod
metadata:
  name: django
  labels:
    app: django
spec:
  containers:
  - name: django
    image: django_app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: secret
            key: SECRET_KEY
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: secret
            key: DATABASE_URL
      - name: DEBUG
        valueFrom:
          secretKeyRef:
            name: secret
            key: DEBUG
      - name: ALLOWED_HOSTS
        valueFrom:
          secretKeyRef:
            name: secret
            key: ALLOWED_HOSTS