apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  SECRET_KEY: MTIzNDVxd2VydHk=
  DATABASE_URL: cG9zdGdyZXM6Ly90ZXN0X2s4czpPd090QmVwOUZydXRAaG9zdC5taW5pa3ViZS5pbnRlcm5hbDo1NDMyL3Rlc3Rfazhz
  DEBUG: RmFsc2U=
  ALLOWED_HOSTS: MTI3LjAuMC4xLDE5Mi4xNjguMC4xLGxvY2FsaG9zdA==
