apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: edu-vasily-casianov
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: vasiliykas/django-site:7ffe865
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: secret
          volumeMounts:
            - name: ssl-cert
              mountPath: /root/.postgresql/root.crt
              subPath: ca.crt
              readOnly: true
      volumes:
        - name: ssl-cert
          secret:
            secretName: postgres-ssl-cert
            items:
              - key: ca.crt
                path: ca.crt
      restartPolicy: Always